import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { getShowcases } from "../api/showcaseApi";

const categories = ["All", "Image", "YouTube", "Reels", "Edits", "Motion Graphics", "Logo", "Thumbnails", "UI/UX", "Social Media", "AI Video"];

const formatKind = (kind) => {
  if (!kind) return "";
  return kind
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/-/g, " ")
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
};

function Work() {
  const [items, setItems] = useState([]);
  const [query, setQuery] = useState("");
  const [activeCategory, setActiveCategory] = useState("All");

  useEffect(() => {
    getShowcases().then((data) => setItems(data.showcases || [])).catch(() => setItems([]));
  }, []);

  const filtered = useMemo(
    () =>
      items.filter((item) => {
        const matchCategory =
          activeCategory === "All" ||
          item.kind?.toLowerCase() === activeCategory.toLowerCase() ||
          item.kind?.toLowerCase().replace("-", " ") === activeCategory.toLowerCase();
        const matchSearch = item.title?.toLowerCase().includes(query.toLowerCase());
        return matchCategory && matchSearch;
      }),
    [activeCategory, items, query]
  );
  const cardAnim = {
    initial: { opacity: 0, y: 24 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, amount: 0.2 },
    transition: { duration: 0.45 }
  };

  return (
    <motion.main className="page work-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
      <h1>Selected Work</h1>
      <p className="page-intro">
        Explore motion graphics, reels, ad edits and cinematic campaigns crafted for brand impact and
        audience retention.
      </p>
      <motion.div className="work-toolbar glass premium-card" {...cardAnim}>
        <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search projects..." />
        <div className="chips">
          {categories.map((item) => (
            <button
              key={item}
              className={activeCategory === item ? "chip active" : "chip"}
              onClick={() => setActiveCategory(item)}
            >
              {item}
            </button>
          ))}
        </div>
      </motion.div>
      <section className="project-grid">
        {filtered.map((item, index) => (
          <motion.div key={item._id} {...cardAnim} transition={{ duration: 0.42, delay: index * 0.04 }}>
            <Link to={`/work/${item.slug}`} className="glass project-card premium-card">
              <img src={item.image?.url || item.image} alt={item.title} loading="lazy" />
              <div className="project-card-content">
                <h3>{item.title}</h3>
                <p>{formatKind(item.kind)}</p>
              </div>
            </Link>
          </motion.div>
        ))}
      </section>
      {!filtered.length && (
        <article className="glass card premium-card empty-state">
          <h3>No projects found for this filter.</h3>
          <p>Try a different category or clear the search to view all available portfolio work.</p>
        </article>
      )}

      <section className="stacked-section">
        <div className="section-head">
          <p className="eyebrow">Performance Snapshot</p>
          <h2>Creative Work That Drives Outcomes</h2>
        </div>
        <div className="stats-grid">
          <motion.article className="glass card premium-card" {...cardAnim}>
            <h3>50+</h3>
            <p>Projects delivered across categories</p>
          </motion.article>
          <motion.article className="glass card premium-card" {...cardAnim}>
            <h3>50M+</h3>
            <p>Total views generated by edited content</p>
          </motion.article>
          <motion.article className="glass card premium-card" {...cardAnim}>
            <h3>4.2x</h3>
            <p>Average uplift on high-converting ad creatives</p>
          </motion.article>
        </div>
      </section>
    </motion.main>
  );
}

export default Work;
